// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADSJSV_b22k7UqB15rD4lxcdSbKoNnpWM',
    appId: '1:59795979623:web:8771f491836be6e4e603c2',
    messagingSenderId: '59795979623',
    projectId: 'real-chat-ad0b8',
    authDomain: 'real-chat-ad0b8.firebaseapp.com',
    storageBucket: 'real-chat-ad0b8.firebasestorage.app',
    measurementId: 'G-568L1XK54Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-s-6v_Ex3PEdkp1dcfD1WJqg05sgDxg',
    appId: '1:59795979623:android:2b771e92527ee34fe603c2',
    messagingSenderId: '59795979623',
    projectId: 'real-chat-ad0b8',
    storageBucket: 'real-chat-ad0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmn74aCOchNfkWW7quGeFUbRpvHBKwIvk',
    appId: '1:59795979623:ios:d3171e232e0a15b4e603c2',
    messagingSenderId: '59795979623',
    projectId: 'real-chat-ad0b8',
    storageBucket: 'real-chat-ad0b8.firebasestorage.app',
    iosBundleId: 'com.example.realChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmn74aCOchNfkWW7quGeFUbRpvHBKwIvk',
    appId: '1:59795979623:ios:d3171e232e0a15b4e603c2',
    messagingSenderId: '59795979623',
    projectId: 'real-chat-ad0b8',
    storageBucket: 'real-chat-ad0b8.firebasestorage.app',
    iosBundleId: 'com.example.realChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADSJSV_b22k7UqB15rD4lxcdSbKoNnpWM',
    appId: '1:59795979623:web:538034a7ce75ce78e603c2',
    messagingSenderId: '59795979623',
    projectId: 'real-chat-ad0b8',
    authDomain: 'real-chat-ad0b8.firebaseapp.com',
    storageBucket: 'real-chat-ad0b8.firebasestorage.app',
    measurementId: 'G-K77WQSHRFG',
  );
}